In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM

C:\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters

In [2]:
data = pd.read_csv(r'sales_history.csv', sep=';')

In [3]:
set(data.article_name)

{'Apfeltasche', 'Brezel', 'Buttercroissant'}

In [5]:
data

                      date     article_name
0      2018-05-18 14:56:26           Brezel
1      2018-05-18 15:03:15  Buttercroissant
2      2018-05-18 15:28:01  Buttercroissant
3      2018-05-18 16:04:45  Buttercroissant
4      2018-05-18 16:29:56           Brezel
5      2018-05-18 16:30:17           Brezel
6      2018-05-18 17:03:06           Brezel
7      2018-05-18 17:04:08  Buttercroissant
8      2018-05-18 18:13:10  Buttercroissant
9      2018-05-18 18:33:57           Brezel
10     2018-05-18 19:12:02  Buttercroissant
11     2018-05-18 19:29:12           Brezel
12     2018-05-18 19:40:15  Buttercroissant
13     2018-05-18 20:02:30           Brezel
14     2018-05-18 20:14:57  Buttercroissant
15     2018-05-18 20:15:37  Buttercroissant
16     2018-05-18 20:16:52           Brezel
17     2018-05-18 20:18:56  Buttercroissant
18     2018-05-18 20:18:56  Buttercroissant
19     2018-05-18 20:27:13           Brezel
20     2018-05-18 20:38:48  Buttercroissant
21     2018-05-18 20:40:28           Brezel
22     2018-05-18 20:42:27           Brezel
23     2018-05-18 20:44:35           Brezel
24     2018-05-18 21:02:03           Brezel
25     2018-05-18 21:08:14           Brezel
26     2018-05-18 21:14:29           Brezel
27     2018-05-18 21:14:29           Brezel
28     2018-05-18 21:25:47           Brezel
29     2018-05-18 21:40:48           Brezel
...                    ...              ...
57792  2019-02-28 17:08:17      Apfeltasche
57793  2019-02-28 17:16:57           Brezel
57794  2019-02-28 17:26:30           Brezel
57795  2019-02-28 17:30:56  Buttercroissant
57796  2019-02-28 17:37:37           Brezel
57797  2019-02-28 17:37:37           Brezel
57798  2019-02-28 17:37:37           Brezel
57799  2019-02-28 17:37:37           Brezel
57800  2019-02-28 17:51:56  Buttercroissant
57801  2019-02-28 17:51:56  Buttercroissant
57802  2019-02-28 18:28:08           Brezel
57803  2019-02-28 18:57:10           Brezel
57804  2019-02-28 18:58:11  Buttercroissant
57805  2019-02-28 18:58:11  Buttercroissant
57806  2019-02-28 18:58:11  Buttercroissant
57807  2019-02-28 19:15:38           Brezel
57808  2019-02-28 19:17:05      Apfeltasche
57809  2019-02-28 19:23:00      Apfeltasche
57810  2019-02-28 19:31:55  Buttercroissant
57811  2019-02-28 19:36:06  Buttercroissant
57812  2019-02-28 19:37:36  Buttercroissant
57813  2019-02-28 20:50:33  Buttercroissant
57814  2019-02-28 21:03:54           Brezel
57815  2019-02-28 21:03:54           Brezel
57816  2019-02-28 21:26:23           Brezel
57817  2019-02-28 21:26:23           Brezel
57818  2019-02-28 21:29:59           Brezel
57819  2019-02-28 22:27:26  Buttercroissant
57820  2019-02-28 22:51:01  Buttercroissant
57821  2019-02-28 22:51:01  Buttercroissant

[57822 rows x 2 columns]

In [6]:
data['date'] = pd.to_datetime(data['date'])
data['date'] = data['date'].dt.strftime('%Y-%m-%d')

In [7]:
data

             date     article_name
0      2018-05-18           Brezel
1      2018-05-18  Buttercroissant
2      2018-05-18  Buttercroissant
3      2018-05-18  Buttercroissant
4      2018-05-18           Brezel
5      2018-05-18           Brezel
6      2018-05-18           Brezel
7      2018-05-18  Buttercroissant
8      2018-05-18  Buttercroissant
9      2018-05-18           Brezel
10     2018-05-18  Buttercroissant
11     2018-05-18           Brezel
12     2018-05-18  Buttercroissant
13     2018-05-18           Brezel
14     2018-05-18  Buttercroissant
15     2018-05-18  Buttercroissant
16     2018-05-18           Brezel
17     2018-05-18  Buttercroissant
18     2018-05-18  Buttercroissant
19     2018-05-18           Brezel
20     2018-05-18  Buttercroissant
21     2018-05-18           Brezel
22     2018-05-18           Brezel
23     2018-05-18           Brezel
24     2018-05-18           Brezel
25     2018-05-18           Brezel
26     2018-05-18           Brezel
27     2018-05-18           Brezel
28     2018-05-18           Brezel
29     2018-05-18           Brezel
...           ...              ...
57792  2019-02-28      Apfeltasche
57793  2019-02-28           Brezel
57794  2019-02-28           Brezel
57795  2019-02-28  Buttercroissant
57796  2019-02-28           Brezel
57797  2019-02-28           Brezel
57798  2019-02-28           Brezel
57799  2019-02-28           Brezel
57800  2019-02-28  Buttercroissant
57801  2019-02-28  Buttercroissant
57802  2019-02-28           Brezel
57803  2019-02-28           Brezel
57804  2019-02-28  Buttercroissant
57805  2019-02-28  Buttercroissant
57806  2019-02-28  Buttercroissant
57807  2019-02-28           Brezel
57808  2019-02-28      Apfeltasche
57809  2019-02-28      Apfeltasche
57810  2019-02-28  Buttercroissant
57811  2019-02-28  Buttercroissant
57812  2019-02-28  Buttercroissant
57813  2019-02-28  Buttercroissant
57814  2019-02-28           Brezel
57815  2019-02-28           Brezel
57816  2019-02-28           Brezel
57817  2019-02-28           Brezel
57818  2019-02-28           Brezel
57819  2019-02-28  Buttercroissant
57820  2019-02-28  Buttercroissant
57821  2019-02-28  Buttercroissant

[57822 rows x 2 columns]

In [8]:
dfs = []

for product in set(data.article_name):
    df = data.loc[data.article_name == product]
    df = df.groupby('date').count()
    df.rename(columns={'article_name':product}, inplace=True)
    dfs.append(df)

df = pd.DataFrame({'date':data['date'].unique()})
for i in range(len(dfs)):
    df = pd.merge(df, dfs[i], on='date', how='outer')

In [9]:
df = df.fillna(0)

In [10]:
df

           date  Apfeltasche  Brezel  Buttercroissant
0    2018-05-18          0.0      25               15
1    2018-05-19          0.0     111               71
2    2018-05-20          0.0     104               87
3    2018-05-21          0.0      59               84
4    2018-05-22          0.0      46               95
5    2018-05-23          0.0      46               86
6    2018-05-24          0.0      68               87
7    2018-05-25          0.0      62               74
8    2018-05-26          0.0      85              104
9    2018-05-27          0.0      90              112
10   2018-05-28          0.0      65               78
11   2018-05-29          6.0      33               86
12   2018-05-30         10.0      65               83
13   2018-05-31         19.0      53              103
14   2018-06-01         14.0      74              107
15   2018-06-02         19.0     102               97
16   2018-06-03         17.0     139              137
17   2018-06-04         32.0     109              131
18   2018-06-05         16.0      82               89
19   2018-06-06         21.0      78               76
20   2018-06-07         12.0      63               88
21   2018-06-08         16.0      49               80
22   2018-06-09         20.0      84               91
23   2018-06-10         20.0     107              118
24   2018-06-11         26.0      88               96
25   2018-06-12         15.0     100               70
26   2018-06-13         16.0      72               82
27   2018-06-14         17.0      75               79
28   2018-06-15         20.0      82               86
29   2018-06-16         17.0      72               83
..          ...          ...     ...              ...
257  2019-01-30         11.0      59               64
258  2019-01-31         12.0      58               75
259  2019-02-01         15.0      56               99
260  2019-02-02         10.0      84               89
261  2019-02-03         10.0      84               91
262  2019-02-04         15.0      62               82
263  2019-02-05         19.0      87               34
264  2019-02-06         20.0      75               67
265  2019-02-07         15.0      63               61
266  2019-02-08         15.0      81               64
267  2019-02-09         12.0      75               63
268  2019-02-10         19.0      81               83
269  2019-02-11         12.0      67               59
270  2019-02-12         13.0      52               60
271  2019-02-13          1.0      47               62
272  2019-02-14         12.0      73               58
273  2019-02-15         15.0      71               74
274  2019-02-16         13.0     113              105
275  2019-02-17         13.0      83              101
276  2019-02-18         17.0      85               55
277  2019-02-19         17.0      83               69
278  2019-02-20         20.0     109               92
279  2019-02-21         11.0      46               77
280  2019-02-22         26.0      58               85
281  2019-02-23          7.0      75               84
282  2019-02-24         14.0      64               62
283  2019-02-25         15.0      73               70
284  2019-02-26          6.0      59               65
285  2019-02-27          5.0      83               72
286  2019-02-28         17.0      68               80

[287 rows x 4 columns]

In [11]:
df.shape

(287, 4)

In [12]:
def split_sequence(data, x_len, y_len):
    X, Y = list(), list()
    i = x_len + y_len
    while i <= len(data):
        x = data[i - x_len - y_len : i - y_len]
        y = data[i - y_len : i]
        X.append(x)
        Y.append(y)
        i+=1
    return X, Y

X,Y = split_sequence(df, 28, 14)

In [13]:
new_X, new_Y = list(), list()
for x in X:
    x = x.drop(['date'], axis=1)
    x = x.values.ravel()
    new_X.append(x)
for y in Y:
    y = y.drop(['date'], axis=1)
    y = y.values.ravel()
    new_Y.append(y)

In [14]:
X_train, X_test, y_train, y_test = train_test_split(new_X, new_Y, test_size=0.33, random_state=42)

In [15]:
X_train = np.asarray(X_train)
X_test = np.asarray(X_test)
y_train = np.asarray(y_train)
y_test = np.asarray(y_test)

In [16]:
X_train = X_train.reshape((X_train.shape[0], 1, X_train.shape[1]))
X_test = X_test.reshape((X_test.shape[0], 1, X_test.shape[1]))

In [28]:
model = Sequential()
model.add(LSTM(168, activation='relu', input_shape=(1, 84)))
model.add(Dense(42))
model.compile(optimizer='adam', loss = 'mse')
history = model.fit(X_train, y_train, epochs=200, verbose=0)

In [30]:
mse = history.history['loss'][-1]
rmse = np.sqrt(mse)
rmse

15.08083912556932

In [33]:
def rmse(predictions, targets):
    return np.sqrt(np.mean((predictions-targets)**2))


predictions = model.predict(X_test)
rmse(predictions, y_test)

17.340831595603774

In [36]:
my_x = df[-28:]
my_x = my_x.drop(['date'], axis=1)
my_x = my_x.values.ravel()
my_x = my_x.reshape((1,1,84))

In [37]:
predictions = model.predict(my_x)
predictions = predictions.reshape((14, 3))
predictions = np.round(predictions)

In [40]:
result = pd.DataFrame(data=predictions,columns=['Apfeltasche', 'Buttercroissant', 'Brezel'])

result.to_csv('sales_prediciton.csv', index=False)